project:
  type: book
  output-dir: _book

execute: 
  freeze: auto

book:
  title: "Data Science for Psychology: Natural Language"
  reader-mode: true
  cover-image: images/cover.png
  favicon: images/favicon.png
  
  page-footer: 
    left: |
      Data Science for Psychology was written by <a href="https://rimonim.github.io">Louis Teitelbaum</a> and <a href="https://almogsi.com">Almog Simchon</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a> and is powered by <a href="https://www.netlify.com/">Netlify</a>
  
  site-url: https://ds4psych.com
  sharing: [twitter, facebook, linkedin]
  repo-url: https://github.com/rimonim/ds4psych
  repo-branch: main
  repo-actions: [source, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    - ethics.qmd

    - part: data-viz.qmd
      chapters: 
        - aesthetics.qmd
        - telling-a-story.qmd
        - word-viz.qmd
        - data-viz-resources.qmd

    - part: data-sources.qmd
      chapters: 
        - experiments.qmd
        - corpora.qmd
        - apis.qmd
        - scraping.qmd
        
    - part: quantification.qmd
      chapters: 
        - look-at-your-data.qmd
        - quanteda.qmd
        - tokenization.qmd
        - word-counting.qmd
        - dla.qmd
        - word-counting-improvements.qmd
        - vectorspace-intro.qmd
        - decontextualized-embeddings.qmd
        - contextualized-embeddings.qmd
        - navigating-vectorspace.qmd
        - lda.qmd
        - linguistic-complexity.qmd
        
    - part: audio-video-image.qmd
      chapters: 
        - transcription.qmd
    
    - resources.qmd

bibliography: references.bib
csl: apa.csl
suppress-bibliography: false

format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 450px
    
    code-link: true
    
    author-meta: "Louis Teitelbaum and Almog Simchon"
    callout-appearance: simple
  pdf: 
    documentclass: scrreprt
    keep-tex: true
    papersize: a4
    fontsize: 11pt
    mainfont: "Libertinus Sans"
    sansfont: "Libertinus Sans"
    monofont: "Courier New"

editor: source

