# Data Visualization {#sec-data-viz .unnumbered}

```{r setup}
#| echo: false
#| include: false

source("_common.R")
```

There are no objective rules for how to make a good data visualization. This is because not all data visualizations have the same purpose.

Here are three common purposes for data visualization:

1.  Getting a quick, intuitive understanding of the data you are working with
2.  Looking for aspects of your data that common statistics might miss (like outliers or nonlinear relationships)
3.  Communicating something to people who don't have a deep understanding of your data

The first two purposes are an important aspects of *exploratory data analysis* (EDA). They will be discussed in @sec-eda. The third one - **communication** - is the topic of this unit.

Communication is hard. It is especially hard for scientists, who often need to balance the needs of multiple target audiences. While insiders in a particular field may want detailed, objective analysis of results and the uncertainty surrounding them, **everyone else wants a story**.

A story is clear, oversimplified and sensational. Stories are what grab people's attention and hold it. Even for experts, stories are what make one study (or news article, or social media post) stand out among many. If you tell a good story, people will want to learn more about the details. If you don't tell a good story, nobody will want to read your supplementary materials. In this way, **all scientists are journalists**.


