# Navigating Vector Space {#sec-navigating-vectorspace}

```{r setup}
#| echo: false
#| include: false

source("_common.R")
```

::: {.callout-important}
## This page is still under construction. Come back soon!
:::

@gunther_etal_2019

## Parallelograms {#sec-parallelograms}

Introduced with word2vec by @mikolov_etal_2013

Glove [@pennington_etal_2014] is designed with this property in mind. Transformer models are not.

In CCR, for example, there’s a difference between agreeing with statements in a questionnaire and actually writing like a questionnaire. How do I know that I’m measuring how anxious/depressed the comments are and not how questionnaire-y they are?
Potential workaround: reverse all of the statements in the questionnaire (as for reverse-coded items), add them to the original questionnaire, and get the average embedding of the construct-neutral questionnaire. Then subtract this embedding from the original questionnaire average embedding.

## Advanced Similarity Measures {#sec-advanced-similarity}

- Jensen–Shannon distance

## Dimension Projection {#sec-dimension-projection}

**An example of using dimension projection in research:** @simchon_etal_2023 collected 10,000 messages from the [r/depression](https://www.reddit.com/r/depression) subreddit, along with a control group of 100 messages each from 100 randomly selected subreddits. They then used a variant of the SBERT model called `all-MiniLM-L6-v2` to compute CCR embeddings (@sec-contextualized-embeddings) of a psychological questionnaire measuring "locus of control," the feeling that you have control over your own life. The questionnaire included items measuring an internal locus of control ("I have control"), and items measuring an external locus of control ("External forces have control"). Simchon et al. constructed an anchored vector to capture the direction between internal and external locus of control, and projected embeddings of the Reddit posts onto that vector to measure how much each post reflected an internal vs. an external locus of control. They found that posts in r/depression exhibited a more external locus of control than posts in the control group.

## Machine Learning Methods {#sec-machine-learning-methods}


@chersoni_etal_2021 used partial least squares regression to map distributional embeddings to human-rated semantic features derived from research in cognitive psychology.
